### PR TITLE
Reduce image size(without reduce qualify) that makes images load faster

### PR DESCRIPTION
**Pull request by SajadRahimi1**
Reduce image size(without reduce qualify) that makes images load faster

### CODE REVIEW

**Comment by vandadnp** [comment]
@SajadRahimi1 thank you for your contribution. I don't see yet a reason to replace the images with new ones. I appreciate you putting time into creating these images. Perhaps if GitHub starts nagging me about image sizes being too much we could revisit this  PR. Thank you again.

**Comment by malmi** [comment]
This would be about accessibility, because if you don't have your fiber internet connection, it would be awesome to load the page in reasonable time, especially when everything has to be loaded all at once, because it is a one-pager. It's not about Github, it's about the people you want to help learn flutter.

**Comment by vandadnp** [comment]
@malmi thank you for your feedback. I had thought about this scenario where people might not want to see the entire landing page and that's why I create dedicated page for each tip only with its source code and image in there in the [tipsandtricks](https://github.com/vandadnp/flutter-tips-and-tricks/tree/main/tipsandtricks) folder. That folder doesn't load any images by default and you have to manually tap on each tip to get its source code and image.

Does this not address the issue to a degree?

Thank you for your input again

**Comment by malmi** [comment]
Thank you for the response. If you approach a repository or send a link to a repository you will probably go to the main page. If i do it here right know (with browser cache disabled) i downloaded 370MB. That is a heavy webpage to open, without knowing what exactly this will provide for me.

**Pull request closed without merging**
