### PR TITLE
Merge pull request #1 from vandadnp/main

### PR DESCRIPTION
**Pull request by OmarBakry-eg**
New updates

### CODE REVIEW

**Comment by OmarBakry-eg** [comment]
New Updates on master repo

**Comment by vandadnp** [comment]
@OmarBakry-eg I don't think this PR was meant to be sent here, am I right?

**Comment by OmarBakry-eg** [comment]
Yes for sure you're write it's just a mistake and I'm sorry for that @vandadnp

**Comment by vandadnp** [comment]
No problem at all @OmarBakry-eg . I will close this PR then. Have a great day

**Comment by OmarBakry-eg** [comment]
Thanks sir .

**Pull request closed without merging**
